name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files
        run: ls -la ${{ github.workspace }}

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/twoyears/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/twoyears/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          always-auth: false
          check-latest: false

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            twoyears/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('twoyears/**/package-lock.json', 'twoyears/**/yarn.lock') }}-${{ hashFiles('twoyears/**.[jt]s', 'twoyears/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('twoyears/**/package-lock.json', 'twoyears/**/yarn.lock') }}-

      - name: Install dependencies
        run: cd twoyears && ${{ env.manager }} ${{ env.command }}

      - name: Build with Next.js
        run: cd twoyears && ${{ env.runner }} next build

      - name: List files after build
        run: ls -la twoyears/.next

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: twoyears/.next

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
